name: Build and Deploy to docs/

on:
  push:
    branches: [main]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build
        run: |
          npm ci
          npm run build  # builds to docs/
          touch docs/.nojekyll # tell gh not jekyll

      - name: Commit and push docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git diff --cached --quiet || git commit -m "Auto-build: deploy to docs"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
